theme = "tusk"
baseurl = "http://CrimsonKindness.github.io"
title = "Crimson Kindness"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
# canonifyURLS = true
languageCode = "en-us"

[params]
  semester = "Spring 2017"
  academicYear = "2016-2017"
